### PR TITLE
Issue 102: Replacing invalid JVM Options

### LINKED ISSUE #102: Invalid JVM Options for JDK 11
### Description
Bookkeeper operator does not work with Bookkeeper 4.11.x. The reason is that Bookkeeper 4.11.x switched to JDK 11 and some of the JVM options used in the Bookkeeper Operator i.e., `AggressiveOpts`, `PrintGCDateStamps` and `MaxRAMFraction` are either deprecated or invalid for JDK 11.

### Importance
must have

### Location
pkg/controller/bookkeepercluster/bookie.go

### Suggestions for an improvement
Deprecated option `XX:MaxRAMFraction` can be replaced with `XX:MaxRAMPercentage`

### PR DESCRIPTION
**Pull request by SrishT**
Signed-off-by: SrishT <Srishti.Thakkar@dell.com>

### Change log description
Removes the deprecated JVM option `-XX:MaxRAMFraction` and replaces it with `-XX:MaxRAMPercentage`. Also replaces the old GC logging options with the `-Xlog` option to configure or enable logging with the Java Virtual Machine (JVM) unified logging framework.

### Purpose of the change
Fixes #102 

### How to verify it
Should be able to successfully deploy bookkeeper 0.8.0 and 0.9.0 using the latest bookkeeper operator

### CODE REVIEW

**Review by anishakj — CHANGES_REQUESTED** [review]
Could you please update the bookkeeper options doc  as well to reflect the changes

**Review by anishakj — APPROVED** [review]
LGTM

File: pkg/controller/bookkeepercluster/bookie.go [hunk 1]
```diff
@@ -338,13 +338,19 @@ func MakeBookieConfigMap(bk *v1alpha1.BookkeeperCluster) *corev1.ConfigMap {
...
 
-	gcLoggingOpts := []string{
-		"-XX:+PrintGCDetails",
-		"-XX:+PrintGCDateStamps",
-		"-XX:+PrintGCApplicationStoppedTime",
-		"-XX:+UseGCLogFileRotation",
-		"-XX:NumberOfGCLogFiles=5",
-		"-XX:GCLogFileSize=64m",
+	gcLoggingOpts := []string{}
+	if match, _ := util.CompareVersions(bk.Spec.Version, "0.9.0", "<"); match {
```
Comment (RaulGracia) [inline pkg/controller/bookkeepercluster/bookie.go:342]: You are comparing Pravega versions here, not Bookkeeper versions, right? But this is the Bookkeeper Operator and it should be related only to Bookkeeper versions. If you do this kind of checks in other places, they will need to be revisited too.

Is there a more generic and precise way of using the right options? For instance, could you make this condition based on the JDK version of the image?

**Review by RaulGracia — CHANGES_REQUESTED** [review]
I don't think that we should mix Pravega versioning with the JVM options to be used in Bookkeeper, which is an independent project with its own versioning.

File: pkg/controller/bookkeepercluster/bookie.go (hunk 1 above)
Comment (SrishT) [reply pkg/controller/bookkeepercluster/bookie.go:342]: @RaulGracia we are comparing bookkeeper image version here and not the pravega version. Seeing that we have Java 11 from Bookkeeper version 0.9 onwards, this check would work as expected

Comment (RaulGracia) [reply pkg/controller/bookkeepercluster/bookie.go:342]: @SrishT I understand this, and this may lead to the conclusion that we should not be creating Bookkeeper images with Pravega versioning, right? Because this pollutes the internal logic of the operator, like in this case. If we agree that this is a Bookkeeper Operator just for Bookkeeper (i.e., independent of Pravega), then you may agree that the version used in this `if` condition has nothing to do with the Bookkeeper versions in the official repo: https://hub.docker.com/r/apache/bookkeeper/tags?page=1&ordering=last_updated

From my point of view, the versions in the link above are the ones that we should be considering, not the ones produced by some arbitrary formatting decision in Pravega. This is making an unnecessary and negative coupling between both projects. You have to keep in mind that a user may want to deploy Bookkeeper alone with this Operator in the same way that happens to the Zookeeper Operator. If we start adding internal logic to the Operator based on Pravega stuff, we are going against this goal.

File: charts/bookkeeper/values.yaml [hunk 2]
```diff
@@ -57,7 +57,13 @@ storage:
...
   memoryOpts: ["-Xms1g", "-XX:MaxDirectMemorySize=2g"]
   gcOpts: []
-  gcLoggingOpts: []
+  ## Unified JVM Logging is used for GC logging from Java 9
+  ## Hence use the following options if the bookkeeper version being deployed
+  ## is based on Java 9 or higher
+  # gcLoggingOpts: ["-Xlog:gc*,safepoint::time,level,tags:filecount=5,filesize=64m"]
+  ## However, if the bookkeeper version being deployed is based on a lower version
+  ## of Java (JDK 8 or below), we should be using the following options for GC logging instead
+  gcLoggingOpts: ["-XX:+PrintGCDetails","-XX:+PrintGCApplicationStoppedTime","-XX:+UseGCLogFileRotation","-XX:NumberOfGCLogFiles=5","-XX:GCLogFileSize=64m"]
```
Comment (RaulGracia) [inline charts/bookkeeper/values.yaml:66]: Why is this the default value? These are the JDK8 values, right? We should use by default the JDK11 ones, which are the default today in Bookkeeper and leave these ones commented.

File: charts/bookkeeper/values.yaml [hunk 3]
```diff
@@ -57,7 +57,13 @@ storage:
 jvmOptions:
   memoryOpts: ["-Xms1g", "-XX:MaxDirectMemorySize=2g"]
   gcOpts: []
-  gcLoggingOpts: []
+  ## Unified JVM Logging is used for GC logging from Java 9
+  ## Hence use the following options if the bookkeeper version being deployed
```
Comment (RaulGracia) [inline charts/bookkeeper/values.yaml:61]: Can you simplify the comment? Something like this should be enough: 
```
## GC logging for Java 9+
gcLoggingOpts: ["-Xlog:gc*,safepoint::time,level,tags:filecount=5,filesize=64m"]
## GC logging for Java 8
# gcLoggingOpts: ["-XX:+PrintGCDetails","-XX:+PrintGCApplicationStoppedTime","-XX:+UseGCLogFileRotation","-XX:NumberOfGCLogFiles=5","-XX:GCLogFileSize=64m"]
```

File: doc/bookkeeper-options.md [hunk 4]
```diff
@@ -67,7 +67,7 @@ Default gcOpts:
 "-XX:-ResizePLAB",
 ```
 
-Default gcLoggingOpts:
+Due to disruptive changes in GC Logging from Java 9, the BookKeeper operator code does not add any default gcLoggingOpts. The appropriate gcLoggingOpts can be provided based on the Java version used within the Bookkeeper version being deployed. If the Java version is 8 or lower, the following options can be provided:
```
Comment (RaulGracia) [inline doc/bookkeeper-options.md:70]: Is this true? The values.yaml file in this PR is actually setting some GC logging options, right? If you don't want to add any GC logging option, then you need to comment also the JDK11 ones in the values.yaml.

**Review by RaulGracia — CHANGES_REQUESTED** [review]

File: charts/bookkeeper/values.yaml (hunk 2 above)
Comment (SrishT) [reply charts/bookkeeper/values.yaml:66]: The bookkeeper version in this values.yaml is 0.7.0 which uses JDK 8
The default values can be changed once pravega/bookkeeper:0.9.0 has been released in open-source and can be used in this values.yaml file

File: charts/bookkeeper/values.yaml (hunk 3 above)
Comment (SrishT) [reply charts/bookkeeper/values.yaml:61]: Sure

File: doc/bookkeeper-options.md (hunk 4 above)
Comment (SrishT) [reply doc/bookkeeper-options.md:70]: The options present in the values.yaml can be easily overridden by the users which is why I have refrained from mentioned those options as the defaults added by the operator.

File: charts/bookkeeper/values.yaml (hunk 2 above)
Comment (RaulGracia) [reply charts/bookkeeper/values.yaml:63]: Pravega 0.9.0 is released already, I think that we need to set this by default for JDK11.

**Review by RaulGracia — CHANGES_REQUESTED** [review]
We have released Pravega 0.9.0 which goes with Bookkeeper 4.11.1, so I think that we need to set by default JDK11 settings. Other than that, it is fine.

**Review by RaulGracia — APPROVED** [review]

File: charts/bookkeeper/values.yaml (hunk 3 above)
Comment (SrishT) [reply charts/bookkeeper/values.yaml]: Done
