### PR TITLE
Issue 59: Fixing Bookie failure

### LINKED ISSUE #59: Bookie failing to restart with InvalidCookieException
### Description
Bookies enter CrashLoopBackOff state after a few hours of running longevity. 
Also while specifying LedgerDirectories for bookkeeper as a comma-separated list of directories `(ledgerDirectories: "/bk/ledgers/l0,/bk/ledgers/l1,/bk/ledgers/l2,/bk/ledgers/l3")`, the following directory structure is observed inside the bookkeeper pod, which which have caused the issue
```
$ ls /bk/ledgers/
l0  l0,  l1  l2  l3
```

### Importance
blocker

### PR DESCRIPTION
**Pull request by SrishT**
Signed-off-by: SrishT <Srishti.Thakkar@dell.com>

### Change log description
After changes done by [this PR](https://github.com/pravega/bookkeeper-operator/pull/44), specifying LedgerDirectories for bookkeeper as a comma-separated list of directories `(ledgerDirectories: "/bk/ledgers/l0,/bk/ledgers/l1,/bk/ledgers/l2,/bk/ledgers/l3")`, creates following directory structure is inside the bookkeeper pods
```
$ ls /bk/ledgers/
l0  l0,  l1  l2  l3

$ ls /bk/ledgers/l0,/bk/ledgers/l1,/bk/ledgers/l2,/bk/ledgers/l3/
lost+found
```
Hence the ledger and journal directories are not getting mounted in the expected manner.

### Purpose of the change
Fixes #59 

### What the code does
Splits the compound string provided to specify comma separated list of `ledgerDirectories` or `journalDirectories` and accordingly creates the mount paths.

### How to verify it
After applying the fix, the comma separated list of directories is correctly mounted as seen below
```
$ ls /bk/ledgers/
l0  l1  l2  l3
```

### CODE REVIEW

File: pkg/controller/bookkeepercluster/bookie.go [hunk 1]
```diff
@@ -207,6 +199,38 @@ func makeBookiePodSpec(bk *v1alpha1.BookkeeperCluster) *corev1.PodSpec {
 	return podSpec
 }
 
+func createVolumeMount(ledgerDirs []string, journalDirs []string, indexDirs []string) []corev1.VolumeMount {
+	var volumeMounts []corev1.VolumeMount
+	for i, ledger := range ledgerDirs {
+		name := JournalDiskName + strconv.Itoa(i)
```
Comment (anishakj) [inline pkg/controller/bookkeepercluster/bookie.go:205]: change to LedgerDiskName

Comment (SrishT) [reply pkg/controller/bookkeepercluster/bookie.go]: done

**Comment by SrishT** [comment]
> Not seeing `lost+found` now. Is IO working?
> Also, if we didnt specify ledger/journal directories, subpath name will come as `/bk/ledger0`. Is IO working fine in that case

With ledger/journal directories specified, I have seen successful I/O run of 10+ hours. Also when ledger/journal directories are not specified, I/O has been seen to be working fine.
