### PR TITLE
Issue 34: Handling znode deletion in non-default namespace

### LINKED ISSUE #34: znodes not deleted when bk cluster deployed in non-default namespace
### Description
The bookkeeper operator fails to delete metadata from zookeeper pods when the bookkeeper cluster is deployed in a non-default namespace.

### Importance
must have

### Location
pkg/controller/bookkeepercluster

### Suggestions for an improvement
_(How do you suggest to fix or proceed with this issue?)_

### PR DESCRIPTION
**Pull request by SrishT**
Signed-off-by: SrishT <Srishti.Thakkar@dell.com>

### Change log description
The bookkeeper operator fails to delete metadata from zookeeper pods when the bookkeeper cluster is deployed in a non-default namespace.

### Purpose of the change
Fixes #34 

### What the code does
It changes the zookeeper url as the operator is unable to resolve it when the svc is presrent in a different namespaces.

### How to verify it
When the bookkeeper cluster which is deployed in a non-default namespace is deleted, the metadata from zookeeper will be successfully deleted which can be confirmed by finding the message `zookeeper metadata deleted` within the bookkeeper operator logs. 
The bookkeeper operator logs post bookkeepr cluster deletion will look like
```
time="2020-04-28T13:15:37Z" level=info msg="Reconciling BookkeeperCluster new/boo-pravega-bk\n"
time="2020-04-28T13:16:07Z" level=info msg="Reconciling BookkeeperCluster new/boo-pravega-bk\n"
time="2020-04-28T13:16:37Z" level=info msg="Reconciling BookkeeperCluster new/boo-pravega-bk\n"
time="2020-04-28T13:16:59Z" level=info msg="Reconciling BookkeeperCluster new/boo-pravega-bk\n"
time="2020-04-28T13:16:59Z" level=info msg="Webhook is handling incoming requests"
time="2020-04-28T13:16:59Z" level=info msg="Webhook is handling incoming requests"
2020/04/28 13:17:44 Connected to 10.100.200.170:2181
2020/04/28 13:17:44 Authenticated: id=216201252599235700, timeout=5000
2020/04/28 13:17:44 Re-submitting `0` credentials after reconnect
2020/04/28 13:17:44 zookeeper metadata deleted
```

### CODE REVIEW

**Comment by pbelgundi** [comment]
@SrishT could you please explain the root cause for this issue?

File: pkg/util/k8sutil.go [hunk 1]
```diff
@@ -82,6 +82,7 @@ func PodAntiAffinity(component string, clusterName string) *corev1.Affinity {
 // Wait for pods in cluster to be terminated
 func WaitForClusterToTerminate(kubeClient client.Client, p *v1alpha1.BookkeeperCluster) (err error) {
 	listOptions := &client.ListOptions{
+		Namespace:     p.Namespace,
```
Comment (pbelgundi) [inline pkg/util/k8sutil.go:85]: @SrishT could you please explain the root cause for this issue? If the zookeeper URI provided in the BK Cluster Spec is incorrect or not resolvable/reachable, BK cluster won;t be able to come up.... so why does this URI work in case of BK cluster and not work when invoked from BK Operator?

Comment (SrishT) [reply pkg/util/k8sutil.go:85]: Both the bookkeeper cluster and the zookeeper cluster were present in a different namespace, which was different from the namespace the operator was deployed in.
Hence the Zookeeper URI was reachable from the bookkeeper cluster but not from the operator.

File: pkg/util/zookeeper_util.go [hunk 2]
```diff
@@ -28,10 +29,22 @@ const (
...
+	zkSvcPort := ""
+	if len(zkUri) >= 1 {
+		zkSvcName = zkUri[0]
+		if len(zkUri) == 1 {
+			zkSvcPort = "2181"
+		} else {
+			zkSvcPort = zkUri[1]
+		}
+	}
+	hostname := zkSvcName + "." + bk.Namespace + ".svc.cluster.local:" + zkSvcPort
```
Comment (pbelgundi) [inline pkg/util/zookeeper_util.go:43]: This fix assumes that Bookkeeper and Zookeeper always run in the same ns. It may be good to make that explicit in the documentation.
