### PR TITLE
Issue 209: Added fix to configure upgrade timeout

### LINKED ISSUE #209: Bookkeeper upgrade is failing in slow environments
### Description

Create a bookkeeper cluster with 4 pods. And upgrade the bookkeeper image. In certain cases, upgrade of bookkeeper is not completing with in 10 min. Due to that only few of the pods are updated to new image and upgrade is failing with error `Progress Deadline exceeded`

### Importance

 must-have

### Location

upgrade.go

### Suggestions for an improvement

Make the upgrade time configurable.

### PR DESCRIPTION
**Pull request by anishakj**
Signed-off-by: anisha.kj <anisha.kj@dell.com>

### Change log description
Added a new field `upgradeTimeout` in CRD to configure the time

### Purpose of the change

Fixes #209

### What the code does

Made changes to configure upgrade time

### How to verify it

Verified bookkeeper upgrade by configuring upgrade time

### CODE REVIEW

File: controllers/upgrade.go [hunk 1]
```diff
@@ -370,7 +370,7 @@ func (r *BookkeeperClusterReconciler) getPodsWithVersion(selector labels.Selecto
 	return pods, nil
 }
 
-func checkSyncTimeout(bk *bookkeeperv1alpha1.BookkeeperCluster, reason string, updatedReplicas int32) error {
+func checkSyncTimeout(bk *bookkeeperv1alpha1.BookkeeperCluster, reason string, updatedReplicas int32, t int32) error {
```
Comment (nishant-yt) [inline controllers/upgrade.go:373]: can we make `t` to `upgradeTimeout`

File: config/crd/bases/bookkeeper.pravega.io_bookkeeperclusters.yaml [hunk 2]
```diff
@@ -2825,6 +2825,10 @@ spec:
                       type: string
                   type: object
                 type: array
+              upgradeTimeout:
+                description: This is used to schedule the timeout value for rollback/upgrade
```
Comment (nishant-yt) [inline config/crd/bases/bookkeeper.pravega.io_bookkeeperclusters.yaml:2829]: suggestion --> `description: This is used to schedule the timeout value in minutes for rollback/upgrade`

**Review by nishant-yt — APPROVED** [review]

File: controllers/upgrade.go (hunk 1 above)
Comment (anishakj) [reply controllers/upgrade.go]: done
