### PR TITLE
Issue 70: I/O fails when bookkeeper operator upgrades and sts get's restarted due to change in the ledger mount path in default case

### LINKED ISSUE #70: I/O fails when bookkeeper operator upgrades and sts get's restarted due to change in the ledger mount path in default case
### Description
I/O fails when bookkeeper operator upgrades and sts get's restarted due to change in the ledger mount path in the default case 

### Importance
must_have

### Location
Changes are needed in bookie.go file

### Suggestions for an improvement
Remove the subpath field in mountpath for ledger when only one ledger is provided  or no ledger directory is provided

### PR DESCRIPTION
**Pull request by Prabhaker24**
Signed-off-by: prabhaker24 <prabhaker.saxena@dell.com>

### Change log description
I/O fails when bookkeeper operator upgrades and sts get's restarted due to change in the ledger mount path in the default case

### Purpose of the change
Fixes #70 

### What the code does
This code ensures that the ledger MountPath doesn't change in case of default case where we don't specify anyMountPath and upgrade the bookeeper-operator or bookkeeper-cluster.

### How to verify it
1) Install Bookkeeper-operator 0.1.1 and deploy bk cluster along with the pravega cluster and upgrade the operator with this fix and then delete the sts and check if the controller is still able to create stream and scopes.
2) Install bookkeeper cluster 0.5.1 along with pravega cluster with bookkeeper operator upgrade the operator with this fix and check if the controller is still able to create streams and scopes.

### CODE REVIEW

File: pkg/controller/bookkeepercluster/bookie.go [hunk 1]
```diff
@@ -203,35 +203,64 @@ func makeBookiePodSpec(bk *v1alpha1.BookkeeperCluster) *corev1.PodSpec {
 	return podSpec
 }
 
-func createVolumeMount(ledgerDirs []string, journalDirs []string, indexDirs []string) []corev1.VolumeMount {
+func createVolumeMount(bk *v1alpha1.BookkeeperCluster, ledgerDirs []string, journalDirs []string, indexDirs []string) []corev1.VolumeMount {
```
Comment (anishakj) [inline pkg/controller/bookkeepercluster/bookie.go:206]: we can remove passing bookkeeper cluster from the function prototype

Comment (Prabhaker24) [reply pkg/controller/bookkeepercluster/bookie.go]: done.

File: pkg/controller/bookkeepercluster/bookie.go [hunk 2]
```diff
@@ -205,33 +205,62 @@ func makeBookiePodSpec(bk *v1alpha1.BookkeeperCluster) *corev1.PodSpec {
 
 func createVolumeMount(ledgerDirs []string, journalDirs []string, indexDirs []string) []corev1.VolumeMount {
 	var volumeMounts []corev1.VolumeMount
-	for i, ledger := range ledgerDirs {
-		name := LedgerDiskName + strconv.Itoa(i)
+	if len(ledgerDirs) > 0 && !strings.EqualFold(ledgerDirs[0], "/bk/ledgers") {
```
Comment (SrishT) [inline pkg/controller/bookkeepercluster/bookie.go:208]: This if block should be executed only if `ledgerDirs` contains a single element. No string comparison would be needed here

Comment (Prabhaker24) [reply pkg/controller/bookkeepercluster/bookie.go]: Done.
