### PR TITLE
Issue 6: Publish events for metadata cleanup failure

### LINKED ISSUE #6: Bookkeeper Operator should send an event if it is not able to delete metadata from zookeeper when BK cluster is deleted
### Description

When Bookkeeper cluster is deleted, the operator attempts to delete BK metadata from zookeeper. If connection to ZK fails or we're not able to delete this metadata for some reason, we just log an error in Bookkeeper logs and do not notify the admin/user that we failed to delete this metadata in any other way.

### Importance
should-have

### Location
reconcileFinalizer() method.

### Suggestions for an improvement
Send a K8s "Error" event when we fail to delete metadata from zookeeper, similar to the events send on Upgrade/Rollback failure.

### PR DESCRIPTION
**Pull request by SrishT**
Signed-off-by: SrishT <Srishti.Thakkar@dell.com>

### Change log description
This change enables the Bookkeeper Operator to emit a K8s Event for failure to cleanup BK metadata from zookeeper at the time of Bookkeeper cluster deletion.

### Purpose of the change
Fixes #6 

### What the code does
The code creates an event and publishes it to the k8s event queue if there is a failure in cleaning up the metadata from the zookeeper nodes after deletion of the bookkeeper cluster.

### How to verify it
An event should get added to kubernetes event queue, whenever zookeeper metadata fails to cleanup after bookkeeper cluster deletion.
The following is the describe output of the event that is created.
```
Name:             ZKMETA_CLEANUP_ERROR-nn6sd
Namespace:        default
Labels:           app=bookkeeper-cluster
                  bookkeeper_cluster=pravega-bk
Annotations:      <none>
API Version:      v1
Event Time:       <nil>
First Timestamp:  2020-04-27T16:53:34Z
Involved Object:
  API Version:   app.k8s.io/v1beta1
  Kind:          Application
  Name:          bookkeeper-cluster
  Namespace:     default
Kind:            Event
Last Timestamp:  2020-04-27T16:53:34Z
Message:         failed to cleanup pravega-bk metadata from zookeeper (znode path: /pravega/pravega): failed to delete zookeeper znodes for (pravega-bk): failed to connect to zookeeper: lookup zookeeper-client on 10.100.200.2:53: no such host
Metadata:
  Creation Timestamp:  2020-04-27T16:53:34Z
  Generate Name:       ZKMETA_CLEANUP_ERROR-
  Resource Version:    864342
  Self Link:           /api/v1/namespaces/default/events/ZKMETA_CLEANUP_ERROR-nn6sd
  UID:                 5b4c3f80-36b5-43e6-b417-7992bc309218
Reason:                ZK Metadata Cleanup Failed
Reporting Component:   bookkeeper-operator
Reporting Instance:    bookkeeper-operator-6769886978-xsjx6
Source:
Type:    Error
Events:  <none>
```

Also verified that the event was indeed consumed by KAHM. 
The call to the KAHM REST API (http://10.243.55.90:17999/v1/api/events?appname=bookkeeper-cluster) returned the following response :
```
[
    {
        "id": "bookkeeper-cluster-default-ZKMETA_CLEANUP_ERROR-nn6sd",
        "type": "Error",
        "message": "failed to cleanup pravega-bk metadata from zookeeper (znode path: /pravega/pravega): failed to delete zookeeper znodes for (pravega-bk): failed to connect to zookeeper: lookup zookeeper-client on 10.100.200.2:53: no such host",
        "reason": "ZK Metadata Cleanup Failed",
        "appname": "bookkeeper-cluster",
        "namespace": "default",
        "acknowledged": "false",
        "labels": {
            "app": "bookkeeper-cluster",
            "app.kubernetes.io/name": "bookkeeper-cluster",
            "bookkeeper_cluster": "pravega-bk"
        },
        "createdon": "2020-04-27 16:53:34 +0000 UTC"
    }
]
```

### CODE REVIEW

File: pkg/controller/bookkeepercluster/bookkeepercluster_controller.go [hunk 1]
```diff
@@ -265,7 +265,14 @@ func (r *ReconcileBookkeeperCluster) reconcileFinalizers(bk *bookkeeperv1alpha1.
 				return fmt.Errorf("failed to update Bookkeeper object (%s): %v", bk.Name, err)
 			}
 			if err = r.cleanUpZookeeperMeta(bk, pravegaClusterName); err != nil {
-				return fmt.Errorf("failed to clean up metadata (%s): %v", bk.Name, err)
+				// emit an event for zk metadata cleanup failure
+				message := fmt.Sprintf("failed to clean up metadata (%s): %v", bk.Name, err)
```
Comment (pbelgundi) [inline pkg/controller/bookkeepercluster/bookkeepercluster_controller.go:269]: Lets clearly state that we failed to cleanup metadata from **zookeeper**  preferably also mention the znode path  "/pravega/<pravega-cluster-name>". So users know what they need to delete manually.

File: pkg/controller/bookkeepercluster/bookkeepercluster_controller.go [hunk 2]
```diff
@@ -265,7 +265,14 @@ func (r *ReconcileBookkeeperCluster) reconcileFinalizers(bk *bookkeeperv1alpha1.
...
+				event := util.NewEvent("CLEANUP_ERROR", bk, "ZK Metadata Cleanup Failed", message, "Error")
```
Comment (pbelgundi) [inline pkg/controller/bookkeepercluster/bookkeepercluster_controller.go:270]: Could we call this ZKMETA_CLEANUP_ERROR... or something similar and also publish the path???
