### PR TITLE
Issue 213: Upgrade of bookkeeper fails intermittently

### LINKED ISSUE #213: Upgrade of bookkeeper cluster is failing intermittently
### Description

Upgrade of bookkeeper cluster is failing intermittently. In operator logs, seeing below output
```
time="2022-06-23T13:56:25Z" level=info msg="syncing cluster version from 4.14.3-8-de07afb7f to 4.14.3-13-378101a"
time="2022-06-23T13:56:25Z" level=info msg="Reconciling BookkeeperCluster store-ns/openshift-upgrade-bk\n"
time="2022-06-23T13:56:25Z" level=info msg="updating statefulset (openshift-upgrade-bk-bookie) template image to 'asdrepo.isus.emc.com:8099/bookkeeper:4.14.3-13-378101a'"
time="2022-06-23T13:56:25Z" level=info msg="failed to reconcile bookkeeper cluster (openshift-upgrade-bk): failed to reconcile cluster status: failed to update cluster status: Operation cannot be fulfilled on bookkeeperclusters.bookkeeper.pravega.io \"openshift-upgrade-bk\": the object has been modified; please apply your changes to the latest version and try again"
{"level":"error","ts":1655992585.8642533,"logger":"controller.bookkeepercluster","msg":"Reconciler error","reconciler group":"bookkeeper.pravega.io","reconciler kind":"BookkeeperCluster","name":"openshift-upgrade-bk","namespace":"store-ns","error":"failed to reconcile cluster status: failed to update cluster status: Operation cannot be fulfilled on bookkeeperclusters.bookkeeper.pravega.io \"openshift-upgrade-bk\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227"}
time="2022-06-23T13:56:25Z" level=info msg="Reconciling BookkeeperCluster store-ns/openshift-upgrade-bk\n"
time="2022-06-23T13:56:25Z" level=info msg="statefulset (openshift-upgrade-bk-bookie) status: 4 updated, 4 ready, 4 target"
2022/06/23 13:56:25 Updating version history adding version 4.14.3-13-378101a
```

### Importance

 must-have

### Location
upgrade.go
### Suggestions for an improvement

Handle upgrade in this scenario as well

### PR DESCRIPTION
**Pull request by anishakj**
Signed-off-by: anisha.kj <anisha.kj@dell.com>

### Change log description
 
In some cases, after updating stateful set, `updatedReplicas` field in sts is not updating correctly. Due to this, the check 
```
if sts.Status.UpdatedReplicas == sts.Status.Replicas &&
		sts.Status.UpdatedReplicas == sts.Status.ReadyReplicas 
```
is succeeding and make upgrade as completed. And pods are not coming up with new image
### Purpose of the change

 Fixes #213

### What the code does

Added additional check to ensure that all  the pods are updated with new version
### How to verify it

Verified that upgrade is working

### CODE REVIEW

File: controllers/upgrade.go [hunk 1]
```diff
@@ -262,10 +267,6 @@ func (r *BookkeeperClusterReconciler) syncBookkeeperVersion(bk *bookkeeperv1alph
 	}
 
 	// If all replicas are ready, upgrade an old pod
```
Comment (nishant-yt) [inline controllers/upgrade.go:269]: Please move the comment `// If all replicas are ready, upgrade an old pod` to line 249

**Review by nishant-yt — APPROVED** [review]
Good to Go
